
TRUNCATE TABLE RT_VIRTUAL_DBS;
TRUNCATE TABLE RT_VDB_MDLS;
TRUNCATE TABLE RT_MDL_PRP_VLS;
TRUNCATE TABLE RT_MDL_PRP_NMS;
TRUNCATE TABLE RT_MDLS;

TRUNCATE TABLE PRINCIPALTYPES;

TRUNCATE TABLE LOGENTRIES;
TRUNCATE TABLE LOGMESSAGETYPES;

TRUNCATE TABLE IDTABLE;

TRUNCATE TABLE AUTHPOLICIES;
TRUNCATE TABLE AUTHPERMISSIONS;
TRUNCATE TABLE AUTHREALMS;
TRUNCATE TABLE AUTHPRINCIPALS;
TRUNCATE TABLE AUTHPERMTYPES;

TRUNCATE TABLE AUDITENTRIES;
TRUNCATE TABLE CS_EXT_FILES;
TRUNCATE TABLE TX_MMXCMDLOG;
TRUNCATE TABLE TX_SRCCMDLOG;
TRUNCATE TABLE TX_SQL;


DROP TABLE RT_VIRTUAL_DBS CASCADE CONSTRAINTS;
DROP TABLE RT_VDB_MDLS CASCADE CONSTRAINTS;
DROP TABLE RT_MDL_PRP_VLS CASCADE CONSTRAINTS;
DROP TABLE RT_MDL_PRP_NMS CASCADE CONSTRAINTS;
DROP TABLE RT_MDLS CASCADE CONSTRAINTS;
DROP TABLE PRINCIPALTYPES CASCADE CONSTRAINTS;
DROP TABLE LOGMESSAGETYPES CASCADE CONSTRAINTS;
DROP TABLE LOGENTRIES CASCADE CONSTRAINTS;
DROP TABLE IDTABLE CASCADE CONSTRAINTS;
DROP TABLE AUTHREALMS CASCADE CONSTRAINTS;
DROP TABLE AUTHPRINCIPALS CASCADE CONSTRAINTS;
DROP TABLE AUTHPOLICIES CASCADE CONSTRAINTS;
DROP TABLE AUTHPERMTYPES CASCADE CONSTRAINTS;
DROP TABLE AUTHPERMISSIONS CASCADE CONSTRAINTS;
DROP TABLE AUDITENTRIES CASCADE CONSTRAINTS;
DROP TABLE CS_EXT_FILES CASCADE CONSTRAINTS ; 

DROP TABLE TX_MMXCMDLOG;
DROP TABLE TX_SRCCMDLOG;
DROP TABLE TX_SQL;

DROP TABLE MMSCHEMAINFO_CA;


