DROP TABLE MMSCHEMAINFO_CA
go

CREATE TABLE MMSCHEMAINFO_CA
(
    SCRIPTNAME        VARCHAR(50) NULL,
    SCRIPTEXECUTEDBY  VARCHAR(50) NULL,
    SCRIPTREV         VARCHAR(50) NULL,
    RELEASEDATE VARCHAR(50) NULL,
    DATECREATED       DATETIME,
    DATEUPDATED       DATETIME,
    UPDATEID          VARCHAR(50) NULL,
    METAMATRIXSERVERURL  VARCHAR(100) NULL
)
go
