<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.example.org/SimpleString/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SimpleString" targetNamespace="http://www.example.org/SimpleString/">
<wsdl:types>
<xsd:schema targetNamespace="http://www.example.org/SimpleString/">
<xsd:element name="NewOperationResponse" type="xsd:string"/>
<xsd:element name="NewOperationRequest" type="xsd:string"/>
</xsd:schema>
</wsdl:types>
<wsdl:message name="NewOperationResponse">
<wsdl:part element="tns:NewOperationResponse" name="NewOperationResponse"/>
</wsdl:message>
<wsdl:message name="NewOperationRequest">
<wsdl:part element="tns:NewOperationRequest" name="NewOperationRequest"/>
</wsdl:message>
<wsdl:portType name="SimpleString">
<wsdl:operation name="NewOperation">
<wsdl:input message="tns:NewOperationRequest"/>
<wsdl:output message="tns:NewOperationResponse"/>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="SimpleStringSOAP" type="tns:SimpleString">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="NewOperation">
<soap:operation soapAction="http://www.example.org/SimpleString/NewOperation"/>
<wsdl:input>
<soap:body parts=" NewOperationRequest" use="literal"/>
</wsdl:input>
<wsdl:output>
<soap:body parts=" NewOperationResponse" use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="SimpleString">
<wsdl:port binding="tns:SimpleStringSOAP" name="SimpleStringSOAP">
<soap:address location="http://www.example.org/"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>
