CREATE VIEW v_f (
    lbjaa bigdecimal NOT NULL OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    heani bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    hmhgi bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    eknlk bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    doehe bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    kgbmc bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    oellk bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ldlhm bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ckjdb bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    dnikm bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    gpfkj bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    oafhf bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    oijho bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ppmai bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    fknbg bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    oinke bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    bjokk bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    cpkdo bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    jlgok bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    kjfhi bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    dnjmb bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    cabec bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    apcmd bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    aomej bigdecimal OPTIONS (SEARCHABLE 'Searchable')
) OPTIONS (MATERIALIZED TRUE)
AS
SELECT * FROM tbl_f;

CREATE VIEW v_y (
    mcncp string(255) OPTIONS (SEARCHABLE 'Searchable'),
    lbngj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    abpap string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    gbeid string(255) OPTIONS (SEARCHABLE 'Searchable'),
    hoidf string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    lcdjm bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    pfcfd bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bnlaa bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    fihil bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bofod bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    gkpja timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    dcpeo string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    ilfdn string(255) OPTIONS (SEARCHABLE 'Searchable'),
    bggnl bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    bpdca string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    eiobk bigdecimal NOT NULL OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bfgac string(1000) OPTIONS (SEARCHABLE 'Searchable'),
    fdgpm string(255) OPTIONS (SEARCHABLE 'Searchable'),
    gmbfj string(50) OPTIONS (SEARCHABLE 'Searchable'),
    opona string(255) OPTIONS (SEARCHABLE 'Searchable'),
    pgdii string(255) OPTIONS (SEARCHABLE 'Searchable'),
    mhbhb string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    cnpom bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    jibjf string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jkcmc bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    aleck bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    dekae bigdecimal(1) OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    nddjo string(50) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    pdkpn string(256) OPTIONS (SEARCHABLE 'Searchable'),
    jdkfi string(20) OPTIONS (SEARCHABLE 'Searchable'),
    bgeik bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bhmmi string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    gaodg timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ejbdg timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ddoaf string(1000) OPTIONS (SEARCHABLE 'Searchable'),
    poaeo string(255) OPTIONS (SEARCHABLE 'Searchable'),
    lmedf string(255) OPTIONS (SEARCHABLE 'Searchable'),
    fhlgb string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ocdai string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    oalgg bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    cnlca string(255) OPTIONS (SEARCHABLE 'Searchable'),
    glcdf timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    dhamm bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    icfbj timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    iamak string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    hgobf timestamp OPTIONS (SEARCHABLE 'Searchable'),
    jlggk string(255) OPTIONS (SEARCHABLE 'Searchable'),
    aafci string(255) OPTIONS (SEARCHABLE 'Searchable'),
    mhmmc string(255) OPTIONS (SEARCHABLE 'Searchable'),
    cenog timestamp OPTIONS (SEARCHABLE 'Searchable'),
    dodla string(255) OPTIONS (SEARCHABLE 'Searchable'),
    imbde bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    gfghh string(255) OPTIONS (SEARCHABLE 'Searchable'),
    bibdd string(255) OPTIONS (SEARCHABLE 'Searchable'),
    clejb bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    meoik integer OPTIONS (SEARCHABLE 'Searchable'),
    odpdb bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    aaekp bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    nnhfn integer OPTIONS (SEARCHABLE 'Searchable'),
    peinc bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    bjmem bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    fbggg timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    kbjfa string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jceba string(255) OPTIONS (SEARCHABLE 'Searchable'),
    cogdd string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jmmhi string(255) OPTIONS (SEARCHABLE 'Searchable'),
    hkjhc string(255) OPTIONS (SEARCHABLE 'Searchable'),
    mnhbj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    inbpg bigdecimal(1) OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    befla string(255) OPTIONS (SEARCHABLE 'Searchable'),
    cgmej string(255) OPTIONS (SEARCHABLE 'Searchable'),
    fcbkh bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    dlgio string(255) OPTIONS (SEARCHABLE 'Searchable'),
    kchjf bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    gcpid bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bojdo bigdecimal(1) OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    fgakc bigdecimal(1) NOT NULL DEFAULT '0 ' OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bofdo bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    nmgkj bigdecimal(10) OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    pnmkd bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ljhbp string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ecfdi bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    heakp bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ajmjj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    dnifh string(2000) OPTIONS (SEARCHABLE 'Searchable'),
    jmafi bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    gpccf string(255) OPTIONS (SEARCHABLE 'Searchable')
) OPTIONS (MATERIALIZED TRUE)
AS
SELECT * FROM tbl_y;

CREATE VIEW v_u (
    hjobj bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    palge string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jfcon bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ghgoj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    penog bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    dkmie bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    pbjjc bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    gjjpd bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    okfkj string(20) OPTIONS (SEARCHABLE 'Searchable'),
    flgib string(5) OPTIONS (SEARCHABLE 'Searchable'),
    ijdmo bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    eeoll string OPTIONS (SEARCHABLE 'Searchable'),
    cbcme string(20) OPTIONS (SEARCHABLE 'Searchable'),
    afecg string(50) OPTIONS (SEARCHABLE 'Searchable'),
    cmkkm string(50) OPTIONS (SEARCHABLE 'Searchable'),
    agoop bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    mdpab string(20) OPTIONS (SEARCHABLE 'Searchable'),
    mkheg string(50) OPTIONS (SEARCHABLE 'Searchable'),
    peefa bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    jdfon bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    jkojm bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ngmlj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ajaab string(255) OPTIONS (SEARCHABLE 'Searchable'),
    gghij bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bbono bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ekega string(255) OPTIONS (SEARCHABLE 'Searchable'),
    lohfc bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    mefcm string(255) OPTIONS (SEARCHABLE 'Searchable'),
    egdob bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    lfocf bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ijjgm string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ndbkk string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ekijk string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jmdci bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    eoadl bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable')
) OPTIONS (MATERIALIZED TRUE)
AS
SELECT * FROM tbl_u;

CREATE FOREIGN TABLE tbl_f (
    lbjaa bigdecimal NOT NULL OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    heani bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    hmhgi bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    eknlk bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    doehe bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    kgbmc bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    oellk bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ldlhm bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ckjdb bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    dnikm bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    gpfkj bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    oafhf bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    oijho bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ppmai bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    fknbg bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    oinke bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    bjokk bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    cpkdo bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    jlgok bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    kjfhi bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    dnjmb bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    cabec bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    apcmd bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    aomej bigdecimal OPTIONS (SEARCHABLE 'Searchable')
);

CREATE FOREIGN TABLE tbl_y (
    mcncp string(255) OPTIONS (SEARCHABLE 'Searchable'),
    lbngj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    abpap string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    gbeid string(255) OPTIONS (SEARCHABLE 'Searchable'),
    hoidf string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    lcdjm bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    pfcfd bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bnlaa bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    fihil bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bofod bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    gkpja timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    dcpeo string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    ilfdn string(255) OPTIONS (SEARCHABLE 'Searchable'),
    bggnl bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    bpdca string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    eiobk bigdecimal NOT NULL OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bfgac string(1000) OPTIONS (SEARCHABLE 'Searchable'),
    fdgpm string(255) OPTIONS (SEARCHABLE 'Searchable'),
    gmbfj string(50) OPTIONS (SEARCHABLE 'Searchable'),
    opona string(255) OPTIONS (SEARCHABLE 'Searchable'),
    pgdii string(255) OPTIONS (SEARCHABLE 'Searchable'),
    mhbhb string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    cnpom bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    jibjf string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jkcmc bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    aleck bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    dekae bigdecimal(1) OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    nddjo string(50) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    pdkpn string(256) OPTIONS (SEARCHABLE 'Searchable'),
    jdkfi string(20) OPTIONS (SEARCHABLE 'Searchable'),
    bgeik bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bhmmi string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    gaodg timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ejbdg timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ddoaf string(1000) OPTIONS (SEARCHABLE 'Searchable'),
    poaeo string(255) OPTIONS (SEARCHABLE 'Searchable'),
    lmedf string(255) OPTIONS (SEARCHABLE 'Searchable'),
    fhlgb string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ocdai string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    oalgg bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    cnlca string(255) OPTIONS (SEARCHABLE 'Searchable'),
    glcdf timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    dhamm bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    icfbj timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    iamak string(255) NOT NULL OPTIONS (SEARCHABLE 'Searchable'),
    hgobf timestamp OPTIONS (SEARCHABLE 'Searchable'),
    jlggk string(255) OPTIONS (SEARCHABLE 'Searchable'),
    aafci string(255) OPTIONS (SEARCHABLE 'Searchable'),
    mhmmc string(255) OPTIONS (SEARCHABLE 'Searchable'),
    cenog timestamp OPTIONS (SEARCHABLE 'Searchable'),
    dodla string(255) OPTIONS (SEARCHABLE 'Searchable'),
    imbde bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    gfghh string(255) OPTIONS (SEARCHABLE 'Searchable'),
    bibdd string(255) OPTIONS (SEARCHABLE 'Searchable'),
    clejb bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    meoik integer OPTIONS (SEARCHABLE 'Searchable'),
    odpdb bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    aaekp bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    nnhfn integer OPTIONS (SEARCHABLE 'Searchable'),
    peinc bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    bjmem bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    fbggg timestamp OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    kbjfa string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jceba string(255) OPTIONS (SEARCHABLE 'Searchable'),
    cogdd string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jmmhi string(255) OPTIONS (SEARCHABLE 'Searchable'),
    hkjhc string(255) OPTIONS (SEARCHABLE 'Searchable'),
    mnhbj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    inbpg bigdecimal(1) OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    befla string(255) OPTIONS (SEARCHABLE 'Searchable'),
    cgmej string(255) OPTIONS (SEARCHABLE 'Searchable'),
    fcbkh bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    dlgio string(255) OPTIONS (SEARCHABLE 'Searchable'),
    kchjf bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    gcpid bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bojdo bigdecimal(1) OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    fgakc bigdecimal(1) NOT NULL DEFAULT '0 ' OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bofdo bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    nmgkj bigdecimal(10) OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    pnmkd bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ljhbp string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ecfdi bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    heakp bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ajmjj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    dnifh string(2000) OPTIONS (SEARCHABLE 'Searchable'),
    jmafi bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    gpccf string(255) OPTIONS (SEARCHABLE 'Searchable')
);

CREATE FOREIGN TABLE tbl_u (
    hjobj bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    palge string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jfcon bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    ghgoj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    penog bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    dkmie bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    pbjjc bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    gjjpd bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    okfkj string(20) OPTIONS (SEARCHABLE 'Searchable'),
    flgib string(5) OPTIONS (SEARCHABLE 'Searchable'),
    ijdmo bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    eeoll string OPTIONS (SEARCHABLE 'Searchable'),
    cbcme string(20) OPTIONS (SEARCHABLE 'Searchable'),
    afecg string(50) OPTIONS (SEARCHABLE 'Searchable'),
    cmkkm string(50) OPTIONS (SEARCHABLE 'Searchable'),
    agoop bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    mdpab string(20) OPTIONS (SEARCHABLE 'Searchable'),
    mkheg string(50) OPTIONS (SEARCHABLE 'Searchable'),
    peefa bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    jdfon bigdecimal OPTIONS (SEARCHABLE 'Searchable'),
    jkojm bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ngmlj string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ajaab string(255) OPTIONS (SEARCHABLE 'Searchable'),
    gghij bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    bbono bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ekega string(255) OPTIONS (SEARCHABLE 'Searchable'),
    lohfc bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    mefcm string(255) OPTIONS (SEARCHABLE 'Searchable'),
    egdob bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    lfocf bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    ijjgm string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ndbkk string(255) OPTIONS (SEARCHABLE 'Searchable'),
    ekijk string(255) OPTIONS (SEARCHABLE 'Searchable'),
    jmdci bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable'),
    eoadl bigdecimal OPTIONS (FIXED_LENGTH TRUE, SEARCHABLE 'Searchable')
);