
package com.sforce.soap.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.6
 * Thu Feb 11 15:37:56 EST 2010
 * Generated source version: 2.2.6
 * 
 */

@WebFault(name = "InvalidQueryLocatorFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidQueryLocatorFault extends Exception {
    public static final long serialVersionUID = 20100211153756L;
    
    private com.sforce.soap.partner.fault.InvalidQueryLocatorFault invalidQueryLocatorFault;

    public InvalidQueryLocatorFault() {
        super();
    }
    
    public InvalidQueryLocatorFault(String message) {
        super(message);
    }
    
    public InvalidQueryLocatorFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidQueryLocatorFault(String message, com.sforce.soap.partner.fault.InvalidQueryLocatorFault invalidQueryLocatorFault) {
        super(message);
        this.invalidQueryLocatorFault = invalidQueryLocatorFault;
    }

    public InvalidQueryLocatorFault(String message, com.sforce.soap.partner.fault.InvalidQueryLocatorFault invalidQueryLocatorFault, Throwable cause) {
        super(message, cause);
        this.invalidQueryLocatorFault = invalidQueryLocatorFault;
    }

    public com.sforce.soap.partner.fault.InvalidQueryLocatorFault getFaultInfo() {
        return this.invalidQueryLocatorFault;
    }
}
