
package com.sforce.soap.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.12
 * Thu Sep 01 08:54:15 CDT 2011
 * Generated source version: 2.2.12
 * 
 */

@WebFault(name = "InvalidQueryLocatorFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class InvalidQueryLocatorFault extends Exception {
    public static final long serialVersionUID = 20110901085415L;
    
    private com.sforce.soap.partner.fault.InvalidQueryLocatorFault invalidQueryLocatorFault;

    public InvalidQueryLocatorFault() {
        super();
    }
    
    public InvalidQueryLocatorFault(String message) {
        super(message);
    }
    
    public InvalidQueryLocatorFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidQueryLocatorFault(String message, com.sforce.soap.partner.fault.InvalidQueryLocatorFault invalidQueryLocatorFault) {
        super(message);
        this.invalidQueryLocatorFault = invalidQueryLocatorFault;
    }

    public InvalidQueryLocatorFault(String message, com.sforce.soap.partner.fault.InvalidQueryLocatorFault invalidQueryLocatorFault, Throwable cause) {
        super(message, cause);
        this.invalidQueryLocatorFault = invalidQueryLocatorFault;
    }

    public com.sforce.soap.partner.fault.InvalidQueryLocatorFault getFaultInfo() {
        return this.invalidQueryLocatorFault;
    }
}
