
package com.sforce.soap.partner;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.2.12
 * Thu Sep 01 08:54:15 CDT 2011
 * Generated source version: 2.2.12
 * 
 */

@WebFault(name = "LoginFault", targetNamespace = "urn:fault.partner.soap.sforce.com")
public class LoginFault extends Exception {
    public static final long serialVersionUID = 20110901085415L;
    
    private com.sforce.soap.partner.fault.LoginFault loginFault;

    public LoginFault() {
        super();
    }
    
    public LoginFault(String message) {
        super(message);
    }
    
    public LoginFault(String message, Throwable cause) {
        super(message, cause);
    }

    public LoginFault(String message, com.sforce.soap.partner.fault.LoginFault loginFault) {
        super(message);
        this.loginFault = loginFault;
    }

    public LoginFault(String message, com.sforce.soap.partner.fault.LoginFault loginFault, Throwable cause) {
        super(message, cause);
        this.loginFault = loginFault;
    }

    public com.sforce.soap.partner.fault.LoginFault getFaultInfo() {
        return this.loginFault;
    }
}
