
DROP TABLE RT_VIRTUAL_DBS
GO
DROP TABLE RT_VDB_MDLS
GO
DROP TABLE RT_MDL_PRP_VLS
GO
DROP TABLE RT_MDL_PRP_NMS
GO
DROP TABLE RT_MDLS
GO
DROP TABLE PRINCIPALTYPES
GO
DROP TABLE LOGENTRIES
GO
DROP TABLE LOGMESSAGETYPES
GO
DROP TABLE IDTABLE
GO
DROP TABLE CFG_STARTUP_STATE
GO
DROP TABLE AUTHPRINCIPALS
GO
DROP TABLE AUTHPERMISSIONS
GO
DROP TABLE AUTHREALMS
GO
DROP TABLE AUTHPOLICIES
GO
DROP TABLE AUTHPERMTYPES
GO
DROP TABLE AUDITENTRIES
GO
DROP TABLE CS_EXT_FILES 
GO 
DROP TABLE CFG_LOCK
GO
DROP TABLE CS_SYSTEM_PROPS
GO
DROP TABLE TX_MMXCMDLOG
GO
DROP TABLE TX_SRCCMDLOG
GO
DROP TABLE TX_SQL
GO


INSERT INTO MMSCHEMAINFO_CA (SCRIPTNAME,SCRIPTEXECUTEDBY,SCRIPTREV,
RELEASEDATE, DATECREATED,DATEUPDATED, UPDATEID,METAMATRIXSERVERURL)
SELECT 'MM_DROP.SQL',USER,'##BUILD_NUMBER##', '##BUILD_DATE##',current_timestamp,current_timestamp,'',''
GO


