DROP TABLE IF EXISTS AUDITENTRIES CASCADE;

DROP TABLE IF EXISTS AUTHPERMISSIONS CASCADE;

DROP TABLE IF EXISTS AUTHPERMTYPES CASCADE;

DROP TABLE IF EXISTS AUTHPRINCIPALS CASCADE;

DROP TABLE IF EXISTS AUTHPOLICIES CASCADE;

DROP TABLE IF EXISTS AUTHREALMS CASCADE;

DROP TABLE IF EXISTS IDTABLE CASCADE;

DROP TABLE IF EXISTS LOGENTRIES CASCADE;

DROP TABLE IF EXISTS LOGMESSAGETYPES CASCADE;

DROP TABLE IF EXISTS PRINCIPALTYPES CASCADE;

DROP TABLE IF EXISTS RT_MDL_PRP_NMS CASCADE;

DROP TABLE IF EXISTS RT_MDL_PRP_VLS CASCADE;

DROP TABLE IF EXISTS RT_MDLS CASCADE;

DROP TABLE IF EXISTS RT_VDB_MDLS CASCADE;

DROP TABLE IF EXISTS RT_VIRTUAL_DBS CASCADE;

DROP TABLE IF EXISTS CS_EXT_FILES
 CASCADE; 
DROP TABLE IF EXISTS TX_MMXCMDLOG
 CASCADE; 
DROP TABLE IF EXISTS TX_SRCCMDLOG
 CASCADE; 
DROP TABLE IF EXISTS TX_SQL
 CASCADE;

DROP TABLE MMSCHEMAINFO_CA
;


